tasks:
  - name: install the remote-signer
    before: |
      sudo sh -c 'curl https://ipfs.anagolay.network/ipfs/QmVwR17T5oT4SsH1gb8T9L9gHe5CsJz2iwhbhWCwPPHgHR > /usr/local/bin/remote-signer && chmod +x /usr/local/bin/remote-signer' \
      && git config --global gpg.program "remote-signer" \
      && git config --global commit.gpgsign true
      
  - name: Install deps
    before: bash .devcontainer/install-deps.sh

  - name: Start containers 
    command: docker-compose up -d
ports:
  - port: 2113
    visibility: public
  - port: 9944
    visibility: public
  - port: 8080
    visibility: private
  - port: 9933
    visibility: private
  - port: 27017
    visibility: private
  - port: 4001
    visibility: private
  - port: 5001
    visibility: private
  - port: 2112
    visibility: private
  - port: 30333
    visibility: private
vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss@0.6.11
    - ms-azuretools.vscode-docker
    - EditorConfig.EditorConfig
    - yzhang.markdown-all-in-one
    - bierner.markdown-mermaid
    - tamasfe.even-better-toml
