version: '3'
services:
  publish:
    image: docker.io/anagolay/microservices-publish:66c0a20 
    env_file: ./env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    links:
      - db
      - ipfs
    ports:
      - $FWD_APP_PORT:3000
  anagolay:
    image: docker.io/anagolay/anagolay:7d277270
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
    volumes:
      - anagolay_data:/data
    command: --dev --no-telemetry --rpc-external --unsafe-ws-external --rpc-cors all
  db:
    image: docker.io/mongo:latest
    env_file: ./env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
    ports:
      - 4001:4001 # ipfs swarm - expose if needed/wanted
      - 5001:5001 # ipfs api - expose if needed/wanted
      - 8080:8080 # ipfs gateway - expose if needed/wanted
    volumes:
      - ipfs_data:/data/ipfs

volumes:
  mongodb_data:
  anagolay_data:
  ipfs_data:
