version: '3'
services:
  app:
    image: anagolay/microservices-publish:latest
    restart: always
    env_file: ./.env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    links:
      - db
    ports:
      - 3000:3000
  db:
    image: docker.io/mongo:latest
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
